# Generated by Django 4.0.4 on 2022-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='D:\\Projects\\project-glass\\media\\img/default.png', upload_to='profile_pics'),
        ),
    ]
