# Generated by Django 4.0.4 on 2022-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0020_remove_glasses_json_data_vehicles_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='v_number',
            field=models.PositiveIntegerField(max_length=15, unique=True, verbose_name='Vehicle NUM'),
        ),
    ]
