# Generated by Django 4.0.4 on 2022-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0022_alter_vehicles_v_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='v_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Vehicle NUM'),
        ),
    ]
