# Generated by Django 4.0.4 on 2022-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0023_alter_vehicles_v_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='v_note',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
