# Generated by Django 4.0.4 on 2022-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0025_alter_vehicles_v_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='v_back_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_face_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_left_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_note',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_right_side',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='v_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='v_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Vehicle NUM'),
        ),
    ]
