# Generated by Django 4.0.4 on 2022-06-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0026_remove_vehicles_v_back_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='g_source',
            field=models.CharField(blank=True, max_length=30, verbose_name='Source of data'),
        ),
    ]
