# Generated by Django 4.0.4 on 2022-06-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0027_glasses_g_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glasses',
            name='g_glass_num',
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_damage_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of damage'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source of data'),
        ),
    ]
