# Generated by Django 4.0.4 on 2022-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0028_remove_glasses_g_glass_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='g_alk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='AlK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_caka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CaKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cakb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CaKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_coka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CoK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_crk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CrK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cuka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CuKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cukb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CuKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_fek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='FeK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_kka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='KKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_kkb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='KKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_mgk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='MsK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_mnk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='MsK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_nak',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='NaK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_sik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_sk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='S K'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_srk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SrK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_tik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='TiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_znka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ZnKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_znkb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ZnKB'),
        ),
    ]
