# Generated by Django 4.0.4 on 2022-07-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0030_alter_glasses_g_damage_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_source', models.CharField(blank=True, max_length=30, null=True, verbose_name='Source of data')),
                ('json_data', models.JSONField(null=True, verbose_name='JSON data')),
            ],
            options={
                'verbose_name_plural': 'Vectors',
                'db_table': 'vectors',
            },
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='json_data',
        ),
    ]
