# Generated by Django 4.0.4 on 2022-07-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_source', models.CharField(blank=True, max_length=30, null=True, verbose_name='Source of data')),
                ('json_data', models.JSONField(null=True, verbose_name='JSON data')),
            ],
            options={
                'verbose_name_plural': 'Vectors',
                'db_table': 'vectors',
            },
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='g_glass_num',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_back_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_face_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_left_side',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_note',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='v_right_side',
        ),
        migrations.AddField(
            model_name='glasses',
            name='g_source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source of data'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_alk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='AlK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_caka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CaKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cakb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CaKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_coka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CoK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_crk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CrK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cuka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CuKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_cukb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CuKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_damage_side',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Damage side'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_damage_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of damage'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_fek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='FeK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_kka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='KKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_kkb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='KKB'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_mgk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='MsK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_mnk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='MsK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_nak',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='NaK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_sik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_sk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='S K'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_srk',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SrK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_tik',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='TiK'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_znka',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ZnKA'),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='g_znkb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ZnKB'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='v_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model'),
        ),
    ]
